server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter-clone
    username: postgres
    password: atuka123
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    mixed: true
  jpa:
    hibernate:
      ddl-auto: update
